In [49]:
#Q1. Create a Pandas Series using a Python list containing values [10, 20, 30, 40, 50].
#After creating the Series, display the values, index labels, and datatype of the Series.
import pandas as pd
nums = [2,6,4,3,6,7,8]
num= pd.Series(nums)
num

0    2
1    6
2    4
3    3
4    6
5    7
6    8
dtype: int64

In [50]:
num.index
num.dtype

dtype('int64')

In [51]:
#Q2. Create a Pandas Series with values [5, 10, 15] and custom index labels ['a','b','c'].
#Access and print the value stored at index label 'b'.
values  = [5, 10, 15]
n = pd.Series((values),index=['a','b','c'])
n
n['b']

np.int64(10)

In [52]:
#Convert the dictionary {'Math':90, 'Physics':85, 'Chemistry':88} into a Pandas
#Series. Display subject names as index.
test ={'Math':90, 'Physics':85, 'Chemistry':88}
k = pd.Series(test)
k

Math         90
Physics      85
Chemistry    88
dtype: int64

In [53]:
#Q4. Create a DataFrame from dictionary containing columns Name, Age and Marks forat least 4 students. Display the complete DataFrame.
data = {'name':['nancy','radha','rimjhim','nisha'],'age':[55,33,23,45],'marks':[88,99,98,89]}
df=pd.DataFrame(data)
df

      name  age  marks
0    nancy   55     88
1    radha   33     99
2  rimjhim   23     98
3    nisha   45     89

In [54]:
#Q5. Create a DataFrame using a list of lists representing Product Name, Price and Quantity columns.
data = [['namkeen',33,3],
['nuts',20,9],
['milk',21,10]]
df = pd.DataFrame(data,columns=['product name','price','quantity'])
df

  product name  price  quantity
0      namkeen     33         3
1         nuts     20         9
2         milk     21        10

In [55]:
#Q6. Using NumPy random module, generate a 5×3 array of random numbers and convert it into a Pandas DataFrame with suitable column names.
#import random
import numpy as np
m = np.random.rand(2,3)
df= pd.DataFrame(m,columns=['col1','col2','col3'])
df

       col1      col2      col3
0  0.106345  0.731472  0.742980
1  0.865694  0.004327  0.572658

In [56]:
#Q7. On any created DataFrame, use head(), tail(), info(), and describe() functions and observe the output of each function
data = {'name':['nancy','radha','rimjhim','nisha'],'age':[55,33,23,45],'marks':[88,99,98,89]}
df=pd.DataFrame(data)
df.head(2)
df.tail(2)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   marks   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

           age      marks
count   4.0000   4.000000
mean   39.0000  93.500000
std    13.9523   5.802298
min    23.0000  88.000000
25%    30.5000  88.750000
50%    39.0000  93.500000
75%    47.5000  98.250000
max    55.0000  99.000000

In [57]:
#Q8.Find and print the shape of the DataFrame, list of column names and index range.
data = {'name':['nancy','radha','rimjhim','nisha'],'age':[55,33,23,45],'marks':[88,99,98,89]}
df=pd.DataFrame(data)
df.shape
df.columns
df.index

RangeIndex(start=0, stop=4, step=1)

In [58]:
#Q9.Demonstrate column selection by extracting a single column as Series and multiple columns as a new DataFrame

In [83]:
#Q10. Perform row selection using both iloc (position■based indexing) and loc(label■based indexing).
data = {
    'name':['nancy','vaishnavi','lado','nikki','radhe'],
    'age':[22,33,12,21,15],
    'marks':[90,93,92,91,90]
}
df = pd.DataFrame(data)
df

        name  age  marks
0      nancy   22     90
1  vaishnavi   33     93
2       lado   12     92
3      nikki   21     91
4      radhe   15     90

In [76]:
#df.iloc[0,1:]
df.loc[2,'marks']

np.int64(99)

In [78]:
#Q11. Apply conditional filtering to display only those rows where Marks are greater than 70.
m = df['marks']>90
m

0    False
1     True
2     True
3     True
4     True
Name: marks, dtype: bool

In [88]:
#Q12. Create a new column named Total by adding 5 bonus marks to the Marks column.
df['total'] = df['marks']+5
df

        name  age  marks  total
0      nancy   22     90     95
1  vaishnavi   33     93     98
2       lado   12     92     97
3      nikki   21     91     96
4      radhe   15     90     95