In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\techcadd\Details.csv")
df.head(4)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card

In [4]:
df.shape

(1500, 7)

In [5]:
df.describe

<bound method NDFrame.describe of      Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0     B-25681    1096     658         7  Electronics  Electronic Games
1     B-26055    5729      64        14    Furniture            Chairs
2     B-25955    2927     146         8    Furniture         Bookcases
3     B-26093    2847     712         8  Electronics          Printers
4     B-25602    2617    1151         4  Electronics            Phones
...       ...     ...     ...       ...          ...               ...
1495  B-25700       7      -3         2     Clothing       Hankerchief
1496  B-25757    3151     -35         7     Clothing          Trousers
1497  B-25973    4141    1698        13  Electronics          Printers
1498  B-25698       7      -2         1     Clothing       Hankerchief
1499  B-25993    4363     305         5    Furniture            Tables

      PaymentMode
0             COD
1             EMI
2             EMI
3     Credit Card
4     Credit Card
...           ...
1495          COD
1496          EMI
1497          COD
1498          COD
1499          EMI

[1500 rows x 7 columns]>

In [6]:
df.info

<bound method DataFrame.info of      Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0     B-25681    1096     658         7  Electronics  Electronic Games
1     B-26055    5729      64        14    Furniture            Chairs
2     B-25955    2927     146         8    Furniture         Bookcases
3     B-26093    2847     712         8  Electronics          Printers
4     B-25602    2617    1151         4  Electronics            Phones
...       ...     ...     ...       ...          ...               ...
1495  B-25700       7      -3         2     Clothing       Hankerchief
1496  B-25757    3151     -35         7     Clothing          Trousers
1497  B-25973    4141    1698        13  Electronics          Printers
1498  B-25698       7      -2         1     Clothing       Hankerchief
1499  B-25993    4363     305         5    Furniture            Tables

      PaymentMode
0             COD
1             EMI
2             EMI
3     Credit Card
4     Credit Card
...           ...
1495          COD
1496          EMI
1497          COD
1498          COD
1499          EMI

[1500 rows x 7 columns]>

In [7]:
df.columns

Index(['Order ID', 'Amount', 'Profit', 'Quantity', 'Category', 'Sub-Category',
       'PaymentMode'],
      dtype='object')

In [8]:
df.ndim

2

In [9]:
df.sample(5)# random values

     Order ID  Amount  Profit  Quantity  Category Sub-Category PaymentMode
1122  B-25958     360      32         3  Clothing        Saree         UPI
346   B-25861      44      14         3  Clothing  Hankerchief  Debit Card
82    B-25675     929     -93         9  Clothing        Saree         COD
524   B-26043      79       5         6  Clothing  Hankerchief  Debit Card
1441  B-25651      11      -4         2  Clothing        Skirt         COD

In [10]:
df.dtypes

Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
dtype: object

In [11]:
df.isna().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
dtype: int64

In [12]:
df['Amount'].mean()

np.float64(291.8473333333333)

In [13]:
df['Amount'].median()

122.0

In [14]:
df['Amount'].mode()

0    27
1    44
Name: Amount, dtype: int64

In [15]:
df['Amount'].corr
df['Amount'].var

<bound method Series.var of 0       1096
1       5729
2       2927
3       2847
4       2617
        ...
1495       7
1496    3151
1497    4141
1498       7
1499    4363
Name: Amount, Length: 1500, dtype: int64>

In [16]:
df.drop_duplicates(inplace=True)
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [17]:
df.shape

(1500, 7)

In [18]:
df.reset_index(drop=True)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI