In [ ]:
import pandas as pd

In [17]:
df = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\techcadd\hospital.zip")
df.head()

,age,length_of_stay_days,num_diagnoses,num_medications,prev_admissions,glucose_level,bmi,has_diabetes,discharge_type,readmitted_30days
0,22.0,28.0,2.0,13.0,4.0,89.1,48.4,1.0,2.0,0
1,44.0,12.0,7.0,11.0,2.0,254.8,23.9,1.0,0.0,1
2,34.0,15.0,9.0,16.0,6.0,270.2,16.7,0.0,1.0,1
3,39.0,15.0,5.0,16.0,6.0,208.6,18.2,0.0,1.0,1
4,62.0,24.0,1.0,6.0,6.0,233.1,44.0,0.0,0.0,1

In [ ]:
df.isnull().sum()

In [ ]:
df.shape

In [ ]:
df.info

In [ ]:
df.describe

In [ ]:
df.columns

In [52]:
df.dtypes

age                    float64
length_of_stay_days    float64
num_diagnoses          float64
num_medications        float64
prev_admissions        float64
glucose_level          float64
bmi                    float64
has_diabetes           float64
discharge_type         float64
readmitted_30days        int64
dtype: object

In [ ]:
df["age"].unique
df["age"] = pd.to_numeric(df["age"])

<bound method Series.unique of 0        22.0
1        44.0
2        34.0
3        39.0
4        62.0
         ...
32295    81.0
32296    55.0
32297    33.0
32298    47.0
32299    58.0
Name: age, Length: 32298, dtype: object>

In [36]:
df["age"].apply(type).value_counts()

age
<class 'str'>      31651
<class 'float'>      647
Name: count, dtype: int64

In [41]:
df["age"]=pd.to_numeric(df["age"],errors='coerce')
df
df["age"].dtype

dtype('float64')

In [42]:
df[df["age"]=="63.0_err"]

Empty DataFrame
Columns: [age, length_of_stay_days, num_diagnoses, num_medications, prev_admissions, glucose_level, bmi, has_diabetes, discharge_type, readmitted_30days]
Index: []

In [44]:
df["age"].isnull().sum()

np.int64(725)

In [51]:
df["age"] = df["age"].fillna(df["age"].mean())
df['age']
df.isnull().sum()

age                      0
length_of_stay_days    648
num_diagnoses          645
num_medications        646
prev_admissions        646
glucose_level          646
bmi                    646
has_diabetes           647
discharge_type         645
readmitted_30days        0
dtype: int64

In [56]:
df["length_of_stay_days"] =df["length_of_stay_days"].fillna(df["length_of_stay_days"].mean())
df["length_of_stay_days"]
df.isnull().sum()

age                      0
length_of_stay_days      0
num_diagnoses          645
num_medications        646
prev_admissions        646
glucose_level          646
bmi                    646
has_diabetes           647
discharge_type         645
readmitted_30days        0
dtype: int64

In [59]:
df["num_diagnoses"] =df["num_diagnoses"].fillna(df["num_diagnoses"].mean())
df["num_diagnoses"]
df.isnull().sum()

age                      0
length_of_stay_days      0
num_diagnoses            0
num_medications        646
prev_admissions        646
glucose_level          646
bmi                    646
has_diabetes           647
discharge_type         645
readmitted_30days        0
dtype: int64

In [ ]:
df["num_medications"] =df["num_medications"].fillna(df["num_medications"].mean())
df["num_medications"]
df.isnull().sum()

In [ ]:
df["prev_admissions"] =df["prev_admissions"].fillna(df["prev_admissions"].mean())
df["prev_admissions"]

0         2.0
1         7.0
2         9.0
3         5.0
4         1.0
         ...
32295    12.0
32296     5.0
32297     7.0
32298    11.0
32299     6.0
Name: num_diagnoses, Length: 32298, dtype: float64

In [65]:
df["glucose_level"] = df["glucose_level"].fillna(df["glucose_level"].mean())
df["glucose_level"]
df.isnull().sum()

age                      0
length_of_stay_days      0
num_diagnoses            0
num_medications        646
prev_admissions        646
glucose_level            0
bmi                      0
has_diabetes           647
discharge_type         645
readmitted_30days        0
dtype: int64

In [67]:
df["bmi"] =df["bmi"].fillna(df["bmi"].mean())
df["bmi"]
df.isnull().sum()

age                      0
length_of_stay_days      0
num_diagnoses            0
num_medications        646
prev_admissions        646
glucose_level            0
bmi                      0
has_diabetes           647
discharge_type         645
readmitted_30days        0
dtype: int64